default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1  
  port: 2020       
  username: postgres
  password: 1234   
  pool: 5

development:
  <<: *default
  database: notebook_development

test:
  <<: *default
  database: notebook_test